# the code container
FROM 4xxi/php-mongo:7.2.2-fpm-alpine3.7 AS deps

# Add our application files here
COPY . /var/www/app
WORKDIR /var/www/app

# Install deps
RUN composer install --no-scripts --prefer-dist --no-dev --no-progress --no-suggest --optimize-autoloader --classmap-authoritative --no-interaction
